server:
  port: 8800
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chino?serverTimezone=GMT-8&useSSL=false&characterEncoding=utf-8
    username: root
    password: RabbitHouse1
  main:
    allow-circular-references: true